services:

  flask:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'python3.12.3/trustapp'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '${FLASK_PORT:-5000}:5000'
      - '${VITE_PORT:-3000}:3000'
    environment:
      WWW_USER: '${WWW_USER:-www-data}'
    volumes:
      - '.:/var/www/html'
    networks:
      - trustapp

networks:
  trustapp:
    driver: bridge
