services:

  flask:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: 'python3.12.3/trustapp'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '${GUNICORN_PORT:-8000}:8000'
    environment:
      WWW_USER: '${WWW_USER:-www-data}'
    volumes:
      - '.:/var/www/html'
    networks:
      - trustapp

networks:
  trustapp:
    driver: bridge
