name: Deploy Flask project

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >> ~/.ssh/config <<EOF
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            Port 2202
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          EOF

      - name: Update app
        run: |
          ssh target << 'EOF'
            # Update code
            cd /srv/trust.tgo.dev/current
            git reset --hard HEAD
            git pull 
            # Update dependencies
            cd ..
            source venv/bin/activate
            pip install --quiet -r current/requirements.txt
            # Update frontend
            cd current/vite
            nvm use --lts
            npm build
          EOF

      - name: Reload NGINX
        run: |
          ssh target << 'EOF'
            sudo nginx -s reload
          EOF