name: Deploy Flask project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >> ~/.ssh/config <<EOF
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            Port 2202
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          EOF

      - name: Update codebase
        run: |
          ssh target << 'EOF'
            cd /srv/trust.tgo.dev/current
            docker compose down
            git pull
          EOF

      - name: Build and run Docker containers
        run: |
          ssh target << 'EOF'
            cd /srv/trust.tgo.dev/current
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install gunicorn
            pip install -r requirements.txt
            docker compose up -d --build --remove-orphans --force-recreate
          EOF

      - name: Reload NGINX
        run: |
          ssh target << 'EOF'
            sudo nginx -s reload
          EOF